# Заполнение таблиц
INSERT INTO faculty (faculty_name) VALUES ('Faculty of Computer Science and Computer Engineering'), 
										  ('Faculty of Economics'), 
                                          ('Institute of Mechanics and Mechanical Engineering');


INSERT INTO `group` (group_name, faculty_id) VALUES ('software engineering', 1), 
													('Computer science and engineering', 1),
													('Information security', 1),
                                                    ('Economy', 2), 
                                                    ('economic security', 2),
                                                    ('applied computer science', 2),
                                                    ('agroengineering', 3),
                                                    ('Mechatronics and robotics', 3),
                                                    ('mechanical engineering', 3);


INSERT INTO student (firstname, surname, age, group_id) VALUES ('Lelush', 'Vermillion', 18, 1),
															   ('Allan', 'Grant', 19, 1),
                                                               ('Abigail', 'Harmon', 19, 1),
                                                               ('Rodger', 'Willis', 20, 1),
                                                               ('Samantha', 'Rice', 25, 1),
                                                               ('Elijah', 'Andrews', 18, 1),
                                                               ('Godwin', 'Phillips', 19, 1),
                                                               ('Roger', 'Kelly', 20, 1),
                                                               ('Patricia', 'Shelton', 19, 1),
                                                               ('Randall', 'Cox', 18, 1),
                                                               ('Archibald', 'Holmes', 19, 1),
                                                               ('Lynn', 'Fisher', 21, 1),
                                                               ('Victor', 'Carr', 35, 1),
                                                               ('Darell', 'Vermillion', 16, 1),
                                                               ('Dick', 'Vermillion', 5, 1),
                                                               ('Corbin', 'Combs', 15, 2),
                                                               ('Biff', 'Murray', 18, 2),
                                                               ('Caleb', 'Murray', 19, 2),
                                                               ('Johnny', 'Murray', 18, 2),
                                                               ('Shepherd', 'Murray', 18, 2),
                                                               ('Ricky', 'Roberson', 18, 2),
                                                               ('Marcus', 'Boyle', 18, 2),
                                                               ('Stuart', 'Benitez', 18, 2),
                                                               ('Tanner', 'Benitez', 18, 2),
                                                               ('Geoff', 'Mcmillan', 18, 2),
                                                               ('Hiram', 'Mcmillan', 31, 2),
                                                               ('Auberon', 'Boyle', 17, 2),
                                                               ('Odin', 'Small', 17, 2),
                                                               ('Gideon', 'Hale', 18, 2),
                                                               ('Tyler', 'Vermillion', 18, 2),
                                                               ('Edison', 'Alvarez', 21, 3),
                                                               ('Greg', 'Vermillion', 18, 3),
                                                               ('Willard', 'Alvarez', 18, 3),
                                                               ('Clinton', 'Vermillion', 18, 3),
                                                               ('Rodger', 'Vermillion', 19, 3),
                                                               ('Jolyon', 'Buck', 19, 3),
                                                               ('Lelush', 'Graves', 18, 3),
                                                               ('Lelush', 'Maynard', 19, 3),
                                                               ('Lelush', 'Ponce', 18, 3),
                                                               ('Lucas', 'Vermillion', 18, 3),
                                                               ('Glanville', 'Vermillion', 17, 3),
                                                               ('Caleb', 'Vermillion', 19, 3),
                                                               ('Cletis', 'Vermillion', 18, 3),
                                                               ('Abner', 'Vermillion', 18, 3),
                                                               ('Lelush', 'Vermillion', 18, 3);